name: ReignOfKingdoms
version: 0.1.0
author: MASTRIO
main: me.MASTRIO.ReignOfKingdoms.Main
api-version: 1.16

commands:
  kingdom:
    usage: /kingdom
    aliases: [kd]
    description: Managing your kingdom and stuff idk
  deb:
    usage: /deb
    description: Debug stuff for Reign Of Kingdoms
  poop:
    usage: /poop
    description: Y E S
