name: ReignOfKingdoms
version: 0.1.0
author: MASTRIO
main: me.MASTRIO.ReignOfKingdoms.Main
api-version: 1.16

commands:
  kingdom:
    usage: /kingdom <balance>
    aliases: [kd]
    description: Managing your kingdom and stuff idk
  debug:
    usage: /debug <balance> <amount-to-add>
    description: Debug stuff for Reign Of Kingdoms
